name: Android CI

on:
  push:
    tags:
      - "v*"

jobs:
  build-av1:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Nuke CMake 3.18.1-g262b901
      run: |
        /usr/local/lib/android/sdk/tools/bin/sdkmanager --uninstall 'cmake;3.18.1'
        sudo rm /usr/local/bin/cmake

    - name: Preparation
      run: |
        EXOPLAYER_ROOT="$(pwd)"
        AV1_EXT_PATH="${EXOPLAYER_ROOT}/extensions/av1/src/main"
        cd "${AV1_EXT_PATH}/jni"
        git clone https://github.com/google/cpu_features
        git clone https://chromium.googlesource.com/codecs/libgav1
        cd "${AV1_EXT_PATH}/jni/libgav1"
        git clone https://github.com/abseil/abseil-cpp.git third_party/abseil-cpp

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

    - name: Build
      run: ./gradlew :extension-av1:build --info

    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: extension-av1
        path: extensions/av1/buildout/outputs/aar/

    - name: Create a new GitHub release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          extensions/av1/buildout/outputs/aar/*

    - name: Publish to GitHub Maven Repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |  
        ./gradlew -Pversion_number=${{ env.RELEASE_VERSION }} :extension-av1:publish --info

